---
- name: Install repos
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.descr }}"
    baseurl: "{{ item.baseurl }}"
  loop: "{{ repos }}"
  when: ansible_facts['distribution'] == "CentOS"

- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

