---
- name: Install repos
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.descr }}"
    baseurl: "{{ item.baseurl }}"
  loop: "{{ repos }}"
- name: Install packages
  yum:
    name: "{{ packages }}"
    state: present

